### ISSUE TITLE
Defaults for job directory inputs don't work

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-data-tier-ui#256]
If you have an input that is directory and the job definition specifies a default for this then the default is not used in the UI.

e.g. where these is this definition:
```
          dataDir:
            title: Directory with sharded data
            type: directory
            default: molecules/sha256
```
The UI shows this:
![image](https://user-images.githubusercontent.com/647419/138899752-602a8a01-d691-42c7-b4e5-4f1fb1702ddc.png)

It should instead show the default value and avoid the user needing to do anything if the default is OK.
All the `dataDir` inputs now have a default value.
